# Accio is a platform to launch computer science experiments.
# Copyright (C) 2016-2018 Vincent Primault <v.primault@ucl.ac.uk>
#
# Accio is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Accio is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Accio.  If not, see <http://www.gnu.org/licenses/>.

# Cf. https://github.com/bazelbuild/rules_go#how-do-i-run-bazel-on-travis-ci

dist: trusty
sudo: required
language: java

env:
  - V=0.11.0

before_install:
  - |
    sysctl kernel.unprivileged_userns_clone=1
    if [[ "${V}" == "HEAD" ]]; then
      # Determine last successful build number. This may change while we are
      # downloading, so it's important to determine ahead of time, in case
      # we need to resume the download.
      CI_BASE="http://ci.bazel.io/view/Bazel%20bootstrap%20and%20maintenance/job/Bazel/PLATFORM_NAME=linux-x86_64/"
      CI_INDEX_URL="${CI_BASE}/lastSuccessfulBuild/"
      wget -q -O build-index.html "${CI_INDEX_URL}"
      CI_BUILD=$(grep '<title>' build-index.html | sed -e 's/^.*#\([0-9]*\).*$/\1/')

      # Determine the artifact name. This is normally, bazel--installer.sh,
      # but it may be, for example, bazel-0.5rc2-installer.sh before a release.
      CI_ARTIFACT=$(grep -o 'bazel-[^\"-]*-installer.sh' build-index.html | head -n 1)
      URL="${CI_BASE}/${CI_BUILD}/artifact/output/ci/${CI_ARTIFACT}"
      rm build-index.html
    else
      URL="https://github.com/bazelbuild/bazel/releases/download/${V}/bazel-${V}-installer-linux-x86_64.sh"
    fi
    wget -O install.sh "${URL}"
    chmod +x install.sh
    ./install.sh --user
    rm -f install.sh

script:
  - |
    bazel \
      --output_base=$HOME/.cache/bazel \
      --batch \
      --host_jvm_args=-Xmx500m \
      --host_jvm_args=-Xms500m \
      test \
      --config=ci \
      --experimental_repository_cache="$HOME/.bazel_repository_cache" \
      --local_resources=400,1,1.0 \
      --test_tag_filters=-dev \
      //accio/...

notifications:
  email: false