# Site settings
title: Accio
email: v.primault@ucl.ac.uk
description: >
  Accio is a location privacy framework.
baseurl: ""
url: "http://yourdomain.com"
nav: index

# Build settings
markdown: kramdown
gems:
  - jemoji
  - jekyll-sitemap
